services:
    elastic:
      container_name: elastic
      image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
      environment:
        - ELASTIC_PASSWORD=123456
        - xpack.security.enabled=true
        - discovery.type=single-node
        - ES_JAVA_OPTS=-Xms512m -Xmx512m
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536
      volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
      networks:
        - es_network
      ports:
        - 9200:9200

    kibana:
      container_name: kibana
      image: docker.elastic.co/kibana/kibana:8.11.1
      #restart: always
      environment:
        - ELASTICSEARCH_HOSTS=http://elastic:9200
      networks:
        - es_network
      ports:
        - 5601:5601
      depends_on:
        - elastic

volumes:
  static_volume:
    driver: local
  elasticsearch-data:

networks:
  es_network:



